apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.cilium.io
    chart: cilium
    targetRevision: 1.17.3
    helm:
      values: |
        k8sServiceHost: 10.96.0.1
        k8sServicePort: 443
        kubeProxyReplacement: true
        ipam:
          mode: kubernetes
        routingMode: native
        autoDirectNodeRoutes: true
        ipv4NativeRoutingCIDR: 10.244.0.0/16
        securityContext:
          capabilities:
            ciliumAgent: [CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID]
            cleanCiliumState: [NET_ADMIN,SYS_ADMIN,SYS_RESOURCE]
        cgroup:
          autoMount:
            enabled: false
          hostRoot: /sys/fs/cgroup
        hubble:
          relay:
            enabled: true
          ui:
            enabled: true
            ingress:
              enabled: false
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /status/terminatingReplicas
