apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resource-requests-limits

spec:
  admission: true
  background: true
  emitWarning: false
  validationFailureAction: Enforce

  rules:
    - name: require-cpu-memory-requests-limits
      skipBackgroundRequests: false

      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
                - Rollout

      exclude:
        any:
          - resources:
              namespaces:
                - argocd
                - kyverno
                - kube-system
                - cert-manager
                - ingress-nginx
                - metallb-system
                - monitoring
                - storage
                - argo-rollouts
                - headlamp
                - chaoskube
                - cilium-spire

      validate:
        allowExistingViolations: false
        message: "Containers must define cpu/memory requests and limits."

        foreach:
          - list: "request.object.spec.template.spec.containers"
            deny:
              conditions:
                any:
                  - key: "{{ element.resources.requests.cpu || '' }}"
                    operator: Equals
                    value: ""

                  - key: "{{ element.resources.requests.memory || '' }}"
                    operator: Equals
                    value: ""

                  - key: "{{ element.resources.limits.cpu || '' }}"
                    operator: Equals
                    value: ""

                  - key: "{{ element.resources.limits.memory || '' }}"
                    operator: Equals
                    value: ""

          - list: "request.object.spec.template.spec.initContainers || `[]`"
            deny:
              conditions:
                any:
                  - key: "{{ element.resources.requests.cpu || '' }}"
                    operator: Equals
                    value: ""

                  - key: "{{ element.resources.requests.memory || '' }}"
                    operator: Equals
                    value: ""

                  - key: "{{ element.resources.limits.cpu || '' }}"
                    operator: Equals
                    value: ""

                  - key: "{{ element.resources.limits.memory || '' }}"
                    operator: Equals
                    value: ""
