apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-readonly-rootfs

spec:
  validationFailureAction: Audit
  background: true
  admission: true

  rules:
    - name: require-readonly-root-filesystem
      skipBackgroundRequests: false

      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
                - Rollout

      validate:
        message: "Containers must use readOnlyRootFilesystem."

        foreach:
          - list: "request.object.spec.template.spec.containers"
            deny:
              conditions:
                any:
                  - key: "{{ element.securityContext.readOnlyRootFilesystem || false }}"
                    operator: Equals
                    value: false

          - list: "request.object.spec.template.spec.initContainers || `[]`"
            deny:
              conditions:
                any:
                  - key: "{{ element.securityContext.readOnlyRootFilesystem || false }}"
                    operator: Equals
                    value: false
