apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-non-root

spec:
  admission: true
  background: true
  emitWarning: false
  validationFailureAction: Audit

  rules:
    - name: require-run-as-non-root

      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
                - Job
                - CronJob
                - Rollout

      validate:
        message: "Containers must run with runAsNonRoot=true."

        foreach:
          - list: "request.object.spec.template.spec.containers"
            deny:
              conditions:
                any:
                  - key: "{{ element.securityContext.runAsNonRoot || request.object.spec.template.spec.securityContext.runAsNonRoot || '' }}"
                    operator: NotEquals
                    value: true

          - list: "request.object.spec.template.spec.initContainers || `[]`"
            deny:
              conditions:
                any:
                  - key: "{{ element.securityContext.runAsNonRoot || request.object.spec.template.spec.securityContext.runAsNonRoot || '' }}"
                    operator: NotEquals
                    value: true
