apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-readonly-rootfs

spec:
  validationFailureAction: Enforce
  background: true
  admission: true

  rules:
    - name: require-readonly-rootfs
      skipBackgroundRequests: false

      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
                - Rollout
      exclude:
        any:
          - resources:
              namespaces:
                - ingress-nginx
                - kube-system
                - storage
                - metallb-system
                - cilium-spire
                - tetragon
                - coturn
                - vpa
                - goldilocks
                - trivy-system
                - authentik
                - immich
      validate:
        allowExistingViolations: false
        message: "Containers must set securityContext.readOnlyRootFilesystem to true."

        foreach:
          - list: "request.object.spec.template.spec.containers"
            deny:
              conditions:
                any:
                  - key: "{{ element.securityContext.readOnlyRootFilesystem || `false` }}"
                    operator: NotEquals
                    value: true

          - list: "request.object.spec.template.spec.initContainers || `[]`"
            deny:
              conditions:
                any:
                  - key: "{{ element.securityContext.readOnlyRootFilesystem || `false` }}"
                    operator: NotEquals
                    value: true
