# apps/rollout-demo-dev.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-demo
  namespace: argocd
spec:
  project: default
  source:
    path: apps/rollout-demo/overlays/dev
    repoURL: https://github.com/yoramvandevelde/k3s-gitops.git
    targetRevision: HEAD
  destination:
    namespace: rollout-demo-dev
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
