apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headlamp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - headlamp.local.sifft.io
      secretName: headlamp-tls
  rules:
    - host: headlamp.local.sifft.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: headlamp
                port:
                  number: 80
