securityContext:
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

config:
  oidc:
    secret:
      create: false
      name: oidc

volumes:
  - name: headlamp-config
    emptyDir: {}
  - name: headlamp-tmp
    emptyDir: {}

volumeMounts:
  - name: headlamp-config
    mountPath: /home/headlamp/.config
  - name: headlamp-tmp
    mountPath: /tmp
