ingress:
  enabled: false

config:
  pluginsDir: /headlamp/plugins

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 100
  runAsGroup: 101

securityContext:
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

volumes:
  - name: headlamp-config
    emptyDir: {}
  - name: headlamp-tmp
    emptyDir: {}

volumeMounts:
  - name: headlamp-config
    mountPath: /home/headlamp/.config
  - name: headlamp-tmp
    mountPath: /tmp
