apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi-iscsi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Zorgt voor nette cleanup bij verwijderen
spec:
  project: default
  source:
    repoURL: https://democratic-csi.github.io/charts/
    chart: democratic-csi
    targetRevision: 0.14.7
    helm:
      values: |
        csiDriver:
          name: "iscsi"
        driver:
          config:
            driver: freenas-api-iscsi
            httpConnection:
              protocol: http
              host: 10.10.10.20
              port: 80
              apiKey: 1-SSYhDEAHJEeyX1ZT60TwOuAD537JMigon7LGZdv7aB9Cj2sjEV7sHNXKv0IAsapO
              allowInsecure: true
            zfs:
              datasetParentName: hba-ssd/iscsi/v
              detachedSnapshotsDatasetParentName: hba-ssd/iscsi/s
            iscsi:
              targetPortal: "10.10.10.20:3260"
              targetGroups:
                - targetGroupPortalGroup: 1
                  targetGroupInitiatorGroup: 1
                  targetGroupAuthType: None
  destination:
    name: in-cluster
    namespace: democratic-csi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
