apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi-nfs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://democratic-csi.github.io/charts/
    chart: democratic-csi
    targetRevision: 0.15.1
    helm:
      releaseName: nfs
      values: |
        csiDriver:
          name: nfs
        driver:
          config:
            driver: freenas-api-nfs
            httpConnection:
              protocol: http
              host: 10.10.10.20
              port: 80
              apiKey: 1-SSYhDEAHJEeyX1ZT60TwOuAD537JMigon7LGZdv7aB9Cj2sjEV7sHNXKv0IAsapO
              allowInsecure: true
            nfs:
              shareHost: 10.10.10.20
              shareAlldirs: false
              shareAllowedHosts: []
              shareAllowedNetworks: []
              shareMaprootUser: root
              shareMaprootGroup: root
              shareMapallUser: ""
              shareMapallGroup: ""
            zfs:
              datasetParentName: hba-ssd/nfs/v
              detachedSnapshotsDatasetParentName: hba-ssd/nfs/s
              datasetEnableQuotas: true
              datasetEnableReservation: false
              datasetPermissionsMode: "0777"
              datasetPermissionsUser: 0
              datasetPermissionsGroup: 0
        storageClasses:
          - name: nfs
            defaultClass: false
            reclaimPolicy: Delete
            volumeBindingMode: Immediate
            allowVolumeExpansion: true
            mountOptions:
              - noatime
              - nfsvers=3
            parameters:
              fsType: nfs
              detachedVolumesFromSnapshots: "false"
        volumeSnapshotClasses:
          - name: nfs
            parameters:
              detachedSnapshots: "true"
  destination:
    name: in-cluster
    namespace: storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
