apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi-iscsi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://democratic-csi.github.io/charts/
    chart: democratic-csi
    targetRevision: 0.15.1
    helm:
      releaseName: iscsi
      values: |
        csiDriver:
          name: iscsi
        controller:
          driver:
            image:
              registry: ghcr.io/democratic-csi/democratic-csi
              tag: v1.9.3
        node:
          driver:
            image:
              registry: ghcr.io/democratic-csi/democratic-csi
              tag: v1.9.3
            iscsiDirHostPath: /etc/iscsi
            iscsiDirHostPathType: "DirectoryOrCreate"
        driver:
          existingConfigSecret: democratic-csi-iscsi-config
          config:
            driver: freenas-api-iscsi
        storageClasses:
          - name: iscsi
            defaultClass: false
            reclaimPolicy: Delete
            volumeBindingMode: Immediate
            allowVolumeExpansion: true
            parameters:
              fsType: ext4
              detachedVolumesFromSnapshots: "false"
        volumeSnapshotClasses:
          - name: iscsi
            parameters:
              detachedSnapshots: "true"
  destination:
    name: in-cluster
    namespace: storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
