---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: democratic-csi-nfs-config
  namespace: storage
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  encryptedData:
    driver-config-file.yaml: AgC1ALZBo9GUT7OGDYlykD7TC1Kb2i+2WBqpvb4jlwiq+78zmjJAjjj1uPRDu26W6AK9YES0TzbdpIJZncbW/v+r2YqDbvjvblxA0+Urta4PRX3MiaJAVgp0X6LKFStC9hO06NL6epmiMC4CrsoGAXW+YsBCTRiEG6K2qtj0SfpzljItxnnhVKlxKaHndzre+h18LAFfaYWrzee+1mH/ICstp3jfqO3Zvdcf147GttUBN1P4mMdzjWLGkx5Fd4WhNoGALTRaflAt5Dk027g8Ab1Fr+sMCbJVVBAS1Orn1BDJSeRahhd0eCoOccoDsXnucspecJxTMCaZ5ncEMNZhyrPO0/lGuukPdFOvqH4njawtAKKvV8OPJJ8kXt2gJk21LVyF/UKxvuKf4WnMxTOK+kPJfrYORqP3PddecVvAgttOh0L+TLHkR1SeFJyxsLb+IL7YoZynWv+4pJyGxA6UUkYvzeX6eHgsSNcIhXBD2JnN5gqEAAjJm7edJWqyj0cK9rB16yaofny/QPMc1CaSHvsXKI2kyWMlnmiC36ZvAP6JB63NtXwtHfw7esQbcVCNIm3VglOgETx9xFECWG/xkBhHuf7aNpBW1jp9DuUXbSRYLo4ZQiK+/04XX24OuIPQu6W7rxwJ0A7XZfmMUgazjrhqzB4A7Fw3dE27oS91oE3R3PpOFG/eiOMsL7V4fFca9VysadaeTIFK+8hHCFlklObxV1tU9NhrtYHh1eNvIznELtoxn2a/lnxPtxPrjO2ZiYhDXjhRuUXpkmmARBQr/7dGoyJn5MOmfQ5Fd9z9P7/oT/gkur2F0crV3vsewth2iv3H4vJrULFO8kZJ4bccM7GAHG0eWM+5XstEwzHRll752oCGdpNC5n5+E2yM80/tHuGNRDnsxx8CuwnSm5qzCa3FxHra+JNl0nNQ4/ZIZ01w0qcZs4DTxVA5/+XFtsIvg6TznkYwP+CQdYjClp4g9M2m75e6auYWKDXdnCerPUqCCqZjw1hkvW505u1hAnkiOLU/xoD1PbPI0n7ZGy1Q1qsZueoSzNYGoT9NrBlQNRV32AVJkyy3g4JeWr5kaOvXaOrW2wl5xtydPBnT6hFznBd4mqqLEswv8eOuI9W+gqjfkqdE5pAMlzQISaJMmt42O6gSToafTqhETPDxqLTqFzmFsCGAF1A41zZeEwUVd1ZOicyU3uPES5LUXqH68tJbyGNQxAIySRV/MTHksfzSN8KBIkvppyjM20qzFRC04XrmM8ZM0l1p2yEYRuOlCTcmkkCdad/Xo0ZWKdIJViBN/Beo2atUu6ADsvbw3TG4su63z+RduxO6G8M7Qfblqe9+qsURGNnMgsMWZvY2w4Xmr3R+gji8rEUgPnblgb04ZVbJkxBZ3vMXCyD8nR5utzmRuex6TXT+NQ1vgzFIVwfSh6Hg1C3OhgBzXvkhDAY5iG+uwnrz6TuhElFdHokH8oA+KZ9CUmyV/0aaQJVSotFo4Wdxc72X7p57cYgq1tAvedn1+4J3VCOVCQXFJTQ4x4pdl/vItoKvrHn35ZI2MIcO8ODBZ3p7KSH9pbc=
  template:
    metadata:
      name: democratic-csi-nfs-config
      namespace: storage
