apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snapshot-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://democratic-csi.github.io/charts/
    chart: snapshot-controller
    targetRevision: 0.3.0
    helm:
      releaseName: snapshot
  destination:
    name: in-cluster
    namespace: storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
