---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: wordpress-prod
spec:
  encryptedData:
    .dockerconfigjson: AgAg74o6DDwQU0HIKoGS2+cQE48Sdmh5B496ppJXoEOWO8NAgWC0P5OWzouLKdY6zyiUNKK6YmtlBUSjpc/Qxk3kQImQALTHDnaWKR0EQzO5mvlmh5WwDLTJ3nzDEpVPj4GbH4CjZ5mL4fr/li88vJirux+KgkfXDBhhM8vSFtStcT9eJB7YHVrfSvC9EZf16CbFcjwU0tfm/wucnOgOQlW5mGlPPpEiBmN44tDDP/6NgNN3is3X+l7qBeigBjXBK+K6ICAnhd0j+wMZq4gAB2brkzY1fWcMunbAfMvN7ay6CAJV+J9Ke4m0kvZ4SRUyjb3NEe8qb2qvH7zhOp2K6/o4J9bOY9RTistC+I2SyIqQsC+hiKu1MVTnGe3gp1S5P9y7aipH8uCKR5etXqgdg0JoHSwMuJO5nkp4zuhSTPHHoMNfwRoX0FxPfZ3gsGUfCNyT7ri/jXBkpOyMbMsINCKSJQfvnXvDUPf/Oo03e6N8df1UPZ6slusczzhGfQXUqGmvqgXsKdA0oqx9Zb3XVLlksC02n3OCnAUWPicX/zx3FH2gd050BVSorGsDiEM9HZr6UScbtPwvAH/qGe++YseJIlwh3SckHGd93F8l7uxdXOZwaLmXOqFhLyMWu8xqGKxGrbuFRPpUglQDbYz6IaZE/DFFAxR+8Eeq2ZonrG+Evzg7gWiI/nYkQHBhS3FSPMxCXq6uf3tXl2I3XFwhnWvK1/wcH6MCFrLM41jWFDTxc3fTl86RAlNwG+VVPg1cTmEGK7TqWSHLKGZb17C/u1KAvMTTlBFwX3mLqSqzhFp9e7m3w0qe9f916k8/raqiUtoth5eQMcs4bnHec4iNiO4Fwzi4lFXhMVWJIZPVyhHiqJB21T9MYlpo0NWiLh9IwbW1e4NRy29rTPzNj0YOi3ALvm5z+njy8beqakGA0AND4N81QsVAuVH3pFRHFekNP20=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: wordpress-prod
    type: kubernetes.io/dockerconfigjson
