apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iscsi-test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: iscsi # Check of dit exact de naam is van je StorageClass
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-test
  template:
    metadata:
      labels:
        app: storage-test
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: my-storage
        # VOEG DIT STUKJE TOE ONDER VOLUME MOUNTS:
        env:
        - name: TEST_USER
          valueFrom:
            secretKeyRef:
              name: opslag-wachtwoord  # De 'name' uit de metadata van je SealedSecret
              key: username           # De 'key' die je in je geheim hebt gezet
        - name: TEST_PASS
          valueFrom:
            secretKeyRef:
              name: opslag-wachtwoord
              key: password
      volumes:
      - name: my-storage
        persistentVolumeClaim:
          claimName: iscsi-test-pvc
---
---
apiVersion: v1
kind: Service
metadata:
  name: storage-test-svc
spec:
  type: LoadBalancer
  selector:
    app: storage-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
