apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recipit-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - recipit.local.sifft.io
      secretName: wildcard-local-sifft-io-tls
    - hosts:
        - recipit.sifft.io
      secretName: wildcard-sifft-io-tls
  rules:
  - host: recipit.local.sifft.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: recipit-svc
            port:
              number: 80
  - host: recipit.sifft.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: recipit-svc
            port:
              number: 80
