apiVersion: v1
kind: ServiceAccount
metadata:
  name: recipit-snapshot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: recipit-snapshot
rules:
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshots"]
  verbs: ["create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: recipit-snapshot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: recipit-snapshot
subjects:
- kind: ServiceAccount
  name: recipit-snapshot
