---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: wordpress-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAyfhDIWprCvQ46yYyxamslTacdPsf2N9VeiMPAtz9XxFxPPx/wVnAQ3AF6zbCD3ocT9kNjxMgjHcw6QH6e1XPrRNrBm6CjADVGMSHMWLx5KfLhYkvpLSGTKRvmVPB28RkqDgoQdpHW4a9EH+gXfPDMQ5okhE5a8OWM1cBxBz2qZSnb7ATHM9/vppOGzRGpZSONcWsha+BHRRitBdG7KcT7yhtyAJN1r9UkAu+9rgJ5ki/gGHn20sDrAW+2xmlIFDTsDpge2C1le+9NZrn1eWtyNhnM42wUuuZeqKb1O9kChxike5vxEr6tY0uwawZw8IsJOIWvRk6UvC7L2l8Y16D46m5HY44S6KZaeS7K2t3+ATMJ87Ga9RCfx4WChit31jajStId2XHmOodQc2+/nRhFIrLraciExZyEVecUN5Gskblk4HMDH9e2hU+H07s5437mzivA5QnHznD8Rzym6x8wDYK33NQFbhC2mjyUVNPjuOcfzgZOR/igpXmzAsLzbwCd703d1ZCQCJLqHJDMlIoh2f0Y0agHwBwyYh6sK5KjHSVCmVeJZR+AR8ZDFKsbHJOMj6yrvyTu59M7vkZ8KKyfSQMcR7Am5/ntz0SZNt17ddWM9Xp7DMz0aXVozF7FJofqhsfLEADMa0Cyaec6ZCXW7pLTAUQE4aTPG2wHBE/HfG2cZG6ZKLeOUyMtuWi7G/Y/hbe/gYcHkeTkGwfmHfekxToqO8RUT1D9ZGJ3QcnKOVhaIkVC/ggpE4VNfl1O1qo0V84XRQWo48yxe2hOrRAt1DyWptlNHHxEnb7faTwyS2FmYZ9+adXn+YoKTH4s9QYf/8rqd71uMh55EZnesySDY7mLx+CCB31VvcQdjWIF1MVQLh/G2+jCfY0iyUhR9d6Q6LXAEiyWdJB0JVzEASiWTmkfNlhovp86AgHfWayvP0vCxDVBjjC2Zn7qjyKClWs=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: wordpress-dev
    type: kubernetes.io/dockerconfigjson
