apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: 3.3.7
    helm:
      values: |
        webhooksCleanup:
          image:
            repository: rancher/kubectl
            tag: v1.30.2

        policyReportsCleanup:
          image:
            repository: rancher/kubectl
            tag: v1.30.2

  destination:
    name: in-cluster
    namespace: kyverno

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
