apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: 3.3.7
    helm:
      values: |
        webhooksCleanup:
          image:
            repository: dtzar/helm-kubectl
            tag: 3.15.4

        policyReportsCleanup:
          image:
            repository: dtzar/helm-kubectl
            tag: 3.15.4
  destination:
    name: in-cluster
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /status/terminatingReplicas
