---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secret
  namespace: authentik
spec:
  encryptedData:
    postgresql_password: AgACNQP+g+XafcnCyfrCg5QFKin5+iTVueVLww7Ohaqz0hw9duSK58YimGuIPQSXF3v24eQTWT7DGcglzsAvfGpvW6DoXlP3uZYjF59R6hg4xMWgKiqtyhaeLhtoOrb/7DlDeUC5NpUG73f3MAAaPmYQ7qBKcC8xR2S7Fm7rJkdCTy5c8fIEO/OOC4HJBn2tTfrCQ9hr7xzheeL1Q7jyu01oCHDkRk/aiH0oPjmGG0ANvdoeNJqDFc2ifoPjpz6B5h+wnIZ4RPBKJVUcZgvNsRqYlHfHxyxotUu6J5BFfXIadIaaDSxxVzjI8KOmyqvVLQ6t7aqhZV4FBKs6I4ygHk9tMPjxWKDG4NS9p3MIF6DWmWVo4ohuZ+rPAL7TsjPJfJgujNwWFsJB31yi88TGVxNSNUCcpYbhQ7oLTwa2MKMLmIrVbmlLKVyEHej43FX05wgy/fGuD/2p+hvfLnCY/Pxla3gy/Wt40WR8yLGlSswfWxyXsJKan6xJyhjJGpXRUxZlSl/p5D451GDLD9xh9hX8zLdmS8CZlvYSpSC15vq4gEtb+QiUUnMUvl9KWLv1y3Q67nat+PWrDaIGVjwEC1WpyHRj0EgMMQglHK+5AVX150zuLhe5BogGN4/OkDQaH7FUG/dKvODmeFh3g/4/BYwgw3tchZw1D7PxsOLz7g/9I+ATe0//uBWzXMuFAjGDd1LFXr1Mp8CDAYup2LxEpY81AOyD/KLz1yEWwVrO6jPfCw==
    secret_key: AgBN8lEuNC2rIepCQ37+4jzUVEOo/qtjff5BkKr9CA3Z+E9EgPkq1PpIGW7MKbeL3Eg1bC5URm6Moo7QM7Dpplf0MaPIMS/b8HtXh7T3ry4cDpk/Q/506ztgxn1QJsjv4MK8SW82Y34Ir/XkxxRlClyVEHl4mKVK4pkYjWY6KDKSYTOJ/XjHlPbIvqm78TGnt0Kk6NzjdbH7wwXIcw4ggznmoFOvYGkjQ+67GPv6wmux83te1CUPR2+MRgVXN+/I21dSiis/u0D5Aqmmh+ySIPCUwGeRynh8EUBhQ7jBF7iKfOCF1tsh9j47hIJym/rejUJTo7JgbGT3hPZPNQ7Mj0vMSBoW0A4CyLJVWgnxFmEBh24gHBXwyOEKTBEGD4orKZuvVTdvoYXRa75JJ2TS0IK/eIi19a23HLZpH5VfC78TrQ/7wV3S+2g4+pc5N/4goifKykkxIVUiVW9Ktgs6/ugx7zHzdlWuWDqMLRFwZkZMfXnr1d03PG35tNCM/uSd2rrFKa5o/VZ/xAzbS8MuwVwFaUHzhVL4E6lGLVV1Ag0gmXbz8kjuKpnmW7TvX2wq3c03GgPnXCRusBmDf3BWSGWvBJ9VgD1+SUt9/VQU/3XwMlF62SgYe9t/BQe8wgwYqupl7h5Z7IibsgTDeGNviHfyYK2M8ztpAAY5sPmZyiXhuCJPwAVJOLzcLqxvjIiqzzyagp5udB1kyvTEKUa/4DXhmVuoW9ewetqoG4e6lijeIDbBNs1ZNnE4/lYLwj0I2NADDQ==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secret
      namespace: authentik
    type: Opaque
