authentik:
  secret_key: ""
  postgresql:
    password: ""

global:
  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-secret
          key: secret_key
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-secret
          key: postgresql_password

server:
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    hosts:
      - authentik.local.sifft.io
    paths:
      - /
    pathType: Prefix
    tls:
      - hosts:
          - authentik.local.sifft.io
        secretName: wildcard-local-sifft-io-tls

worker:
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

postgresql:
  enabled: true
  auth:
    username: authentik
    database: authentik
    existingSecret: authentik-secret
    secretKeys:
      userPasswordKey: postgresql_password
  primary:
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    persistence:
      enabled: true
      storageClass: iscsi
      size: 5Gi

redis:
  enabled: true
  auth:
    enabled: false
  master:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
    persistence:
      enabled: false
