apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - sealed-secret.yaml
  - prosody.yaml
  - jicofo.yaml
  - jvb.yaml
  - web.yaml
  - ingress.yaml
  - network-policy.yaml
