apiVersion: v1
kind: ServiceAccount
metadata:
  name: trivy-ui
  namespace: trivy-ui
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trivy-ui
rules:
  - apiGroups:
      - aquasecurity.github.io
    resources:
      - vulnerabilityreports
      - configauditreports
      - clusterconfigauditreports
      - rbacassessmentreports
      - clusterrbacassessmentreports
      - infraassessmentreports
      - clusterinfraassessmentreports
      - exposedsecretreports
      - sbomreports
      - clustersbomreports
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trivy-ui
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trivy-ui
subjects:
  - kind: ServiceAccount
    name: trivy-ui
    namespace: trivy-ui
