apiVersion: v1
kind: ConfigMap
metadata:
  name: tuwunel-config
data:
  tuwunel.toml: |
    [global]
    # Setting "*" in the contains allowlist allows all domains for URL previews
    url_preview_domain_contains_allowlist = ["*"]
