---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tuwunel-secret
  namespace: tuwunel-dev
spec:
  encryptedData:
    registration_token: AgBKX4vwvpQhdm8OGb+UTUOG3kUXP4g6k/ACZllyztfKNrxMn3xa7QVwgYg84d8d+0VW6Ygxwg8fwl0JItJr8fWzdt1qe3QfVaXJXMoBMjReiRy1f9+0uDYzDL+47z1KHRixEJv2etYBYMuj3HMYTckbwCbWTxife1NGrvKC/S0P0ift/5ugwy0zlEXadNJwqBvZdBTNEak2LJp3lQBWsjDopuHlp1s9u+L4yXXb6SH7JafzmgWioK7a9JqF7N+Dnr8GY+TzW1g5zfZ+fmYT2CAe4amrH4sUzjsgrLtEvY294i244GvvHGyAnaN9kHeYThd1NPRsAU5DgGvU69QmeDxI6w0hAdfP9qMbu4pZwZyUmEv+vLVO8QPCafRonbDp/RSLL8wcOPr6uvW+JZZ5DJ+MvvpKnQBWKJfIzY0plSuWpP6bmKNoRS3ZInM/LewFqXhLgprAXYBXawq7B8Ghq4IF7zTXmALjGCB6r5j4JxtHEZz9tx8qeMbgJMGCQC+Lwp5cnOBeA++8jQ3QIhgXrZRUvtqVRDkdTJ2eud+RuSP+tZc1BAdLr0GvuGkxGVlHWlkxH43bU18TidJrLniPe3jWED11cMeIUhtCSxyQCiQ3DMfTQkVVv1MH3NB2fDEr2XdYJhaC3tf41vuWpGi6LwR44JNUh3bhnC0fi1FTQwdIw2g41VCmgVBkM1DroqwJNNdfVFh0D30ywFy8PFbUY/ET/PM6yU/0Avs=
  template:
    metadata:
      creationTimestamp: null
      name: tuwunel-secret
      namespace: tuwunel-dev
