---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tuwunel-turn-secret
  namespace: tuwunel-dev
spec:
  encryptedData:
    turn_secret: AgBwnKQlfFe17exvlpuNiDmm6YYfXzf0L2DNNOx5GpwbBHWnWeEl0ej3L/00gsHMXc0GGq5LWlLLCnsTiZbGWGD3D+XzJoPpam6irjfwTJZtqxX5d+uWxIonoBMW4ddRO7uEn98tvTE18Cr5808U5mhus/Dh8rxJgZbsp4lP9WG+4fiOCNfeS8fsuwT3q76re72qckPv5F6qMiVqfIh3ACGV9T2jpDvhC0vuYItzaHMBm7J5xc12KkrOVOvqUcCBpdI3E1NGY3L7GdZjAuoSUl+gyHjll53Tvs63iQVVR2oqUFHUm5lBBFJojOSEuOdY5TgyM09Cwk8WVRIJ6+8Zwc+m7talBM0/Bui0QB5JSkv3A7t9+OSOFWfa2rWl2E8sBRaHI8LGb5Q6KEsWoHSnkx2dloltrcIyPHMHbPd8+dNGaF48UMkOQc0LDtHcTCGVXMIQ7w2NEvQKPD5BGoCd6oT1zhDpwfNHGRj9vEaF4PyPWy0/x+ixyXTbRYNKnGISzYkaADgCTzAJg5l557vnPT/ezvW0Is9oZe5CyFKg602tcZ7CiFFD1Zt8TYvGvRUzXRcHhMzc8DZP4I3nbO7VNDQBA7/HfdkPI8SzC/7dflKyCn39reP80a0rxziq0WGIy14CKXQFT969KnEb9ZV1cGV1Za1HNrGmMAGK3uzcfpiB0wfOOx7fF6KPdlREmI/afdMXtElYSqJzKNAGqi9owOYVDhtvZ+x9DNrF2fRkujWETtE/9bqv66jKr3+K5efE5y1V7SkxnwVu+YFWqPrNLuWT
  template:
    metadata:
      creationTimestamp: null
      name: tuwunel-turn-secret
      namespace: tuwunel-dev
