apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tetragon
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.cilium.io
    chart: tetragon
    targetRevision: 1.7.0
    helm:
      values: |
        tetragon:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          prometheus:
            enabled: true
            port: 2112
            serviceMonitor:
              enabled: true
              labelsOverride:
                release: kube-prometheus-stack
        tetragonOperator:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          prometheus:
            enabled: true
            port: 2113
            serviceMonitor:
              enabled: true
              labelsOverride:
                release: kube-prometheus-stack
  destination:
    name: in-cluster
    namespace: tetragon
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /status/terminatingReplicas
