apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 69.3.2
    helm:
      values: |
        grafana:
          admin:
            existingSecret: grafana-admin-secret
            userKey: admin-user
            passwordKey: admin-password

          persistence:
            enabled: true
            type: sts
            storageClassName: nfs
            size: 2Gi

          service:
            type: LoadBalancer
            annotations:
              metallb.universe.tf/loadBalancerIPs: 10.10.99.81

          containerSecurityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault

          sidecar:
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
              seccompProfile:
                type: RuntimeDefault

        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: nfs
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi
          service:
            type: LoadBalancer
            annotations:
              metallb.universe.tf/loadBalancerIPs: 10.10.99.82

        alertmanager:
          service:
            type: LoadBalancer
            annotations:
              metallb.universe.tf/loadBalancerIPs: 10.10.99.83

  destination:
    name: in-cluster
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
