---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  encryptedData:
    admin-password: AgCmV57OjflTahZPxX/8TvYXqInPYtTFyB9uc/Si7Q9r75NvshEoFLzOo0KW6bAiO5Bmw6OER1nGxKY+a+Svvyf4iEvuAyDR3389idzaziipNnTQnIam8etLkdGikCn9XzTffa1p6WmksDRDnXdpLsBdvtHpYfn+lm+yEyeZcMAF/xa5Xfr+Od11OnqO4vua1kDm3claUopNwFU3E98MX2VXYip9ZrJc0/ZeY/G9PtrE8A6CfoQjeMLG0gbpFfddO+bNhRqfIYpcZv6g3B67n/7SM5hBT+9xXZ2wbkDXfY/Dd9TrB9+Agzw7VhZ+WqTwSSCUhtabtD/uHKHUeqZ3oKaKePAA4SSloGrjYKYi3fl6NVrgep+wd9HyYXvagwp2e92RNDE36QCauWXrxjQ26kpJkDQ7SujZYZGKcurIWl62eE3YSB5pg7A0orBDWt08+jk18JwmB0pBbWLCE/nKDFYFrvWsBAKvqbyYIBVb52453Jfl/TX8hkGc4BAjQnWGsk89QkcC+QbkGg1TpEpUGjWk1s018pyZUJjzewCcAlxf7THbxf/bnsv0PRjNVpOKSVJ9vz+jiDswxlqFXzGSIf1cmLmBCXGqtlgKyUdO4VeOrf4KIbGfFzrYw3fr5m+JmbBZkS6m2Q80KADZrLukEvGAO03RgnuEMPfQ7/csEXDl69Lg7+/HKGkXz/ZTki0w3vIy2UxRCESmAw==
    admin-user: AgAzzc35Yq+Tf/1pTsMEoZuf3mLtAJLsji/R/P+IEMWp2B4V1E80nVkqdCbSsVa6DswlpOeatUBN2i4QIumdOtNpj+WZJO8lkDtOmkk1uBBjuqeGcImlW3oNzCOFKrApm84Npxf+za5qf8O3MiwuSRYt+E54rpdG0+1XkeHx3VE6YVmWzWDfUViKUQekJM3ZIo4PxUy+kwEzpSzqS7WemwxslZ8Oqr5eQ4B38BSXjYhx1aMmk6RYG06+BT1CbUdCmNrGQBxCNeB8EQmxhU5wKttl/kZTJCP61xNgccrRZUxzeKrNcRKTmKJ9SLvYwmSr8ii0m1Ow3Pb4hZn5HHYwJgsxujCF5qUKWKPVVfMGrB0N38wAyCxWXowoSNWikYyMfx52CaSLJvX9G2BDnKx98QC4Wv1OUze8C4iG2CI+qeQOP3i6o/oQiRZh3nidKgdBrutJRTinhepkNXO4dMDloCSOicuqvM5wauAwVQ2OX75MQWnUg2vqZUCzzU5N4lCLNfGnWxhnJL4ZFcONMaNyUSLpBAJ5W15uyOJwEo9QKr/jWA/y1o9Ut08tbe8V3Vq57CFDg2dAPbo2/5UPA2Bt1OmV3ovRLmw66BLw+vk2BAwkRc6ZG+eyGDI2Uq0g0KUGdXxXw+hnnk/hia6RXuLJsDRPw0SKzCbcKOF0VaMbAU+AZ1zm0uvlJ71lIWHTFDmXkb9eIndkjQ==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
