---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-oidc-secret
  namespace: monitoring
spec:
  encryptedData:
    client_secret: AgA9ZaowSO7zoDzSCzao8FTlGBY27f8b0RERnqFjc6UT7tjzL9d/7VstC5Q6yBD66zPz003e/SzbBpA0eVrCEA3PziG001giQy4l+rnKDT+X7q+741390nmBgqA+uJyNDjU+Pvsm07grMGbEYu/QU5ONQHF/4zd9Rp/pfSbKm3OzLRcbyqZAC9Bzl9prC0PjTEPXz5e0mDiZElSgznfpOTY7x+TBugoiWItiXzSNKD/dRHwlfrUHVKKABMBw6g7oGEpScLQsv2hMEqDtSx+1TOGPU/Fvk2wFTf01lBJgCNMbea53FFyCVlVZkFAqEhd+AS5SnNNZJugZ2q+ZqcgmFGOoCR6l3+9UowrBVRiZr6MjyDXSQ+8Q2LSAW55pwE5k7KLlzNU9cqizi7bDRYTjT37nN0P0y5K6FfgG4sfiJTSxfthCqsLBxyL7qZ9ZFXZdeMsa0EFsevQO2bgGE4iPmEdLEjJ9p9Vo/RyLwVh9bkpN22BF/il9LXS94MA3/x34yhygeGJQgCCdFankUDl2zDgPpe6eqjMYbPdZfRcBMYvkXjoVu7oPG5KTYGfAExsGKVVgnnqslf2I5etC3U9DDPlcn2ejTP3Nz5vvohCKkB8GhpeFH/8wxLtzXQzKZptHVyNHHOt5N+ibpEIZCpt/Jbl4s6me9LHCPcmiJD4FY9kaBV6Z09qiazig4hsRrLD0Ax7c3LQrxfSUWvlGPu/OpatM6vcUOhS/s5ojFpqjGQ60J0iBZDUBefY4IYb7pGj+g9bmozwaddXaftekjjmb4cab6+0Q+HOSq9pJCxvfpoYYcKaNwZWwkREarEXRdu6z76lT+4m2sghysRmDy5WUi9XXJDABTaklkeY/GVJzBkJ/hg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-oidc-secret
      namespace: monitoring
    type: Opaque
