---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-oidc-secret
  namespace: forgejo-dev
spec:
  encryptedData:
    client_id: AgAfGKS8a9c/Wmwx7wN97AgTgRmzD3deTvGrtYVkeiWRM6FFht6fIugFG5PupjDMtyMjb2rMyAMOglW3n0eLI06DOd7QE4+gWEuGEMuREer+DblynTiRC9/+ivk2zRDTn4+nhSW5pp8/2jIqC1WpMeq6tgo35+HqAJmKwcTLVwWYvX0lZarTAmaTGMPwNU8R31X61Dilq0BYB5mgr+x08kFBymlOsRMGFLWHSwwSduajollX2IYyFJJElgIst5xA4S2kllxatQvmOIi7FFMLKuw6OCD3YTcfgCGBjnNw8DtuYXlAQdqReWGzZ9+5TSf4gbaxtRQh9lIYwAlrqFK4jpemFg7chj2Hz+lOJ1O2TELYKbmuUJ6uLTFVPnYusoVHnDdF9QpYiN3PbBU1Pwf33AkllKQoXlLNRtLolHJ13/9eet6O3aK6ODct6tp1T3iWagFeMZ43qNnK83CP9OpA0n9I/wlYMa3iT02gEVTXrd0K/CF5NALSTQss9IU1K3VKG9fretSV19wzNTHP9SRcZ/uOkI8kTn7FK16PCTBqTj+FcUY46ufN2DoCQkuhOc5SdP+ibc1VC8yYdpHBfXXPOv6u6ttD6KEkEPb/ky1Ulq9hCDVyxdYE8oYNKO0n0kmmfUjYa8toTt6JOzXwq6WewqLWRrsio8UeoZL9/WB3MlD2IFl9U4B8Hn3pOdxeQPSBWQQxOCJNLsCWxdw0TbariIjgI+zmofVzbC9K+eFtybs07JIp1mNvF6xl
    client_secret: AgCcVGRtPao/QdJlEhsnLAeolWMANpyCgm4x5QcawkC2MztIV98FwKYjgYXOWJl9r5okkN1qcyUKDpkVgFwF93nY1HtkomTLtQtF8R3n82s/CBcgOJaC7rj7RzHBnWkKi/GMQNwXWpWm1sOQHqCK2MUlHbF3S+orUPta+mYj45VZnu3xlsloUW9DTuzcCyhV0Jod+H+T2UlhCOqeFDFeywP216N0BuUTBEK4d+0O4RwezKDVaqUOIaiyOuogoaXEcRoUCJycuq2Yitgv1Y9pe1ytHlAkpykkDKhCB/xTi/3TNmlCt05paYayaeiOVSEsyj68twyUHBvdU2Hij3vIb6W0nxNxHo7IexwwDKnz/NfVwEiXePrQCF1pb6o8Ty82XL7HKJwV5bev/pfDDVIITpzXHRGodWvl/N7aXS8lWHeFxw2F7Ys6DL7ZdnPufcMZ0n+CIcVimEMI6vHW6UxhtcvRcTZMmk3NiNwYD5pEuPJUQ00l2qsJ6GBFL1Dc2dJZqcs0QOp6MqYBze7UaxpziapTkhGw3lHNXVtx54e8GiChdgnIZxAfbeFQeIOaeb8alh0mxezE1ogiv+oLsuv1fpBQ4W+3e9uLdwWlaQY4n1WOfZhQOftD5AHMVvopBeen6E/r67vQIirB3qASspXQBmRXG6ADKHInR3uhBtRhPrU2yB2RqyfSsWi7ltvVkaN2jvmMQGnEENqaZ9C8Tj1qxSUSC//lvAeeo3wTNGk4KT314Zz5o1PBhR0ue1u0wdg5XArt2VZEG/dtVwS9r+S7FAByhbWMdGkLA/1gU96anijW0GGa6/X/5hQlqAmFE94HxJ0ElVXDoYf445OoGmn4zEWkS2thhK6Cp+GDxREiQKHeOQ==
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-oidc-secret
      namespace: forgejo-dev
