replicaCount: 1

persistence:
  enabled: true
  storageClass: iscsi
  size: 10Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

initContainers:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false

gitea:
  admin:
    existingSecret: forgejo-admin-secret
    passwordMode: initialOnlyRequireReset

  config:
    server:
      DOMAIN: git.local.sifft.io
      ROOT_URL: https://git.local.sifft.io/
      SSH_DOMAIN: git-ssh.sifft.io
      SSH_PORT: 22
      SSH_LISTEN_PORT: 2222
      START_SSH_SERVER: true

    database:
      DB_TYPE: sqlite3

    service:
      DISABLE_REGISTRATION: true

service:
  http:
    type: ClusterIP
    port: 3000

  ssh:
    type: LoadBalancer
    port: 22
    targetPort: 2222
    annotations:
      metallb.universe.tf/loadBalancerIPs: 10.10.99.84

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: git.local.sifft.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - git.local.sifft.io
      secretName: forgejo-tls
