---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: coturn-secret
  namespace: coturn
spec:
  encryptedData:
    external-ip: AgA8v/6NXbOIfPBnODd/QFESxArKND8EqhgRIwv3QWTMfvEe9uvwLxVylDZ6kOkX6kUtbt2Uu7g/RyZKvkM5+X9+cXdCCKLMx2nIIVfTHlaLe7IM8FjR/JKBAqwukEBql4Raju3KF07F1azMSrZgE7PJUFncXKDQ5q7gPeBqXS7CJnK06y9YauUdvFtewzhtGMhtNxmKfT/tBhUSi7byRqIQLmcG/VKSSSY/bDlxfnb2yYSblI2TnK74bDIti5I9KMgHxSorgnbSsb5/9GO//e78ixoUOez/pogkIgfSFJFZcvZ9CgC+oa2PtJQo77Ok3i8w7xRlliTvpIGvyg8CoAcZ6Jc0lkDC9jFW5lVsoIKRvj8+d+UxJ7IxeRtYLXTtrlzl+gJ/KCb91LeK6FkE6Rbj9RwMI/D1Rn80jWcggrkivOkKfMZhp03ULENJVXnvoaiAmFZkWYWeR8ki902woL5QCDuzfW7hJ152x4NKuT+T09ONr8OUeox5J3MHmVlipWuCVbbenNwtNNdh+wcRVzw63u2a9m0wuiRyWWxoQ2oDivT8i3KUafxim45iPyxyUEzUywDkHU9rwcbUfR5QsczLIxKkxuGpvkDlABim3dUuqrVMxLNeyInzXxvP1FhWbnObz8kCIvOr2T0pvpM81g1URDSoeNe4H73Ew1iWdFsJCNnK4f7dNzjiPifwR4yJNoyxweJjfPp1mv3j6GzyuA==
    turn-secret: AgC4q+bg01T6R/T5tGiEzuoXWD9jKT2CLwWabxjvOCKbvVPSvHt9bXmGvephEcEPWNrJQFRvg5MSIo2icsbEjy/Ps1XncRa1aWbFCQ+rrORtG0y5UNLGly7o8TWnR5giJmiivROxjalroYID9WAT3muvHujpT9IWc6vWKDWLsgRD4o/qzUXTWQxm76NRk9hXefn9iTjB2mfF6GSpjt3eq7eebeiOQYqB0ORh9p2IlDEEGFJ4zEMz+uTdQwohCqhwRbVSf90cY3Xe4uUMKENxAPEov/7/Y384PaoyrDvHqOfEC5ygspH4QqRXNqPrCN6M0RnFmo6+b3OyXNbx5iiZ6mV6GIZW9Kp7Ldwj1w5BiRiYhBiFsnS04Fof4bTO3jmrrfm40eWKLmeU1KQkvZ2vSXp5U+wQxFRC70LYHAilKSOWF34HZvVpqgFVtLUtCM/McYl4NVC8VEpSPwO6jZN8STfyLU3Oatj4PVm9LBNnmuXR4+t4kPc/wNlXSZSRauWn9+OIWJsXY/64dBK50bunuizP3oxY9IQVPYZy+k3y3ZXYCQYxPE/f0toJmspaQoKgF/2J+2ASsLwZmHDeAjYfdtQvy0kZ1rB8aJGPhV2KmAEm3RXnkBQtXpr2kU/SolFOUsvt6KNi4Hhy4fCxgoXbDIu935bwkAodaXWfYMI75t3RcDE9SW5byuiiI6XNZFsuBfsRRSl9F2Wyf4sGDpIgeBujgqNFewh9XZak2FP6DgvdD3xeTuM65BeKD3LymIYuQ29IbNJ7Ak2DcZIIAmKbTdvV
  template:
    metadata:
      creationTimestamp: null
      name: coturn-secret
      namespace: coturn
