apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wordpress-secret
spec:
  encryptedData:
    mysql-root-password: # JIJ MOET DIT GENEREREN
    mysql-user: # JIJ MOET DIT GENEREREN
    mysql-password: # JIJ MOET DIT GENEREREN
  template:
    metadata:
      name: wordpress-secret
      labels:
        app: wordpress
