apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-iscsi-prod # (en test-iscsi-prod voor de andere)
  namespace: argocd
spec:
  project: default  # <--- VOEG DEZE REGEL TOE
  source:
    path: apps/test-iscsi/overlays/prod
    repoURL: https://github.com/yoramvandevelde/k3s-gitops.git
    targetRevision: HEAD
  destination:
    namespace: test-dev
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
