apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/yoramvandevelde/k3s-gitops.git
    targetRevision: HEAD
    path: infrastructure/networking
    directory:
      include: "{metallb-ippool.yml,metallb-l2.yml}"
  destination:
    name: in-cluster
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
