apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-local-sifft-io
  namespace: cert-manager
spec:
  secretName: wildcard-local-sifft-io-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.local.sifft.io"
