apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-local-sifft-io
  namespace: cert-manager
spec:
  secretName: wildcard-local-sifft-io-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "argocd,kube-system,headlamp,wordpress-dev,wordpress-prod,forgejo-dev,recipit-dev,authentik,monitoring,trivy-ui"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.local.sifft.io"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-sifft-io
  namespace: cert-manager
spec:
  secretName: wildcard-sifft-io-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "argocd,recipit-dev,tuwunel-dev"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.sifft.io"
