apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: codeberg.org/forgejo-contrib/forgejo-helm
      chart: forgejo
      targetRevision: 17.0.1
      helm:
        valueFiles:
          - $values/apps/forgejo/values-dev.yaml

    - repoURL: https://github.com/yoramvandevelde/k3s-gitops.git
      targetRevision: HEAD
      ref: values

  destination:
    name: in-cluster
    namespace: forgejo-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
