apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://headlamp-k8s.github.io/headlamp/
      chart: headlamp
      targetRevision: 0.26.0
      helm:
        valueFiles:
          - $values/apps/headlamp/values-dev.yaml
    - repoURL: https://github.com/yoramvandevelde/k3s-gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    name: in-cluster
    namespace: headlamp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
