apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp-manifests
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/yoramvandevelde/k3s-gitops.git
    targetRevision: HEAD
    path: apps/headlamp
  destination:
    name: in-cluster
    namespace: headlamp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
