apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://immich-app.github.io/immich-charts
      chart: immich
      targetRevision: 0.11.1
      helm:
        valueFiles:
          - $values/apps/immich/values-dev.yaml
    - repoURL: oci://registry-1.docker.io/bitnamicharts
      chart: postgresql
      targetRevision: 18.6.4
      helm:
        releaseName: immich-postgresql
        values: |
          auth:
            username: immich
            database: immich
            existingSecret: immich-secret
            secretKeys:
              userPasswordKey: db-password
              adminPasswordKey: db-postgres-password
          primary:
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 1Gi
            persistence:
              enabled: true
              storageClass: iscsi
              size: 20Gi
    - repoURL: https://github.com/yoramvandevelde/k3s-gitops.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/yoramvandevelde/k3s-gitops.git
      targetRevision: HEAD
      path: apps/immich
      directory:
        exclude: "values*.yaml"
  destination:
    name: in-cluster
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /status/terminatingReplicas
