apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-postgresql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 17.1.0
    helm:
      values: |
        auth:
          username: immich
          database: immich
          existingSecret: immich-secret
          secretKeys:
            userPasswordKey: db-password
            adminPasswordKey: db-postgres-password
        primary:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
          persistence:
            enabled: true
            storageClass: iscsi
            size: 20Gi
  destination:
    name: in-cluster
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
