apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wordpress-prod
resources:
  - ../../base
  - sealed-secret.yaml
  - sealed-ghcr-pull-secret.yaml
patches:
  - target:
      kind: PersistentVolumeClaim
      name: mysql-pvc
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 50Gi
  - target:
      kind: PersistentVolumeClaim
      name: wordpress-pvc
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 20Gi
