---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: wordpress-prod
spec:
  encryptedData:
    .dockerconfigjson: AgBHPyXpHtrryozWHwPfwO/4W4jFUERvSBp5HLMMsZmBiDcp3Ie7oyE1WERoRwFxF5OuQeexopt125TL8sKlapAFJdf5WYiVdt71tC2hnRdEKWlql9JDwyOIAmfWSzF3rF9K+D5VkYUe0U+G7+nUlLA4cwDuL/kzMgHXADk0ReGW1rONKuOG1wbZBwyFrxMNCiYJN7HqyROUadIfvsRsgJgzuz+A4xHL1Fc+DyKQjBfJayIgDIW+WwlwgrhPuCk9PmrkGNadu7kuD6bh7oxZtYos1R4oTeBRg3Hq41Qx0wMZsP904iWqvjmhf8Qc5BfCEMeue1TrxmFxKlx5f944V3IEUIIsfJoP0t/LSSugYRgGH5GheWI0+i7BJW3M5n9wDJquh1T+mTwivBrpf+6T3xI9n9VdLcR9rKjtk6ntm2Tce6np92UFNJhl1JlQvxKVbOB2TO1HjFcAC7FRLL8okujlZzlcjef2t72Hszi00h3rSb7uDV/srY0kctiQjD7jCRYWDL8cXEWCMpVZ3hx6SO/gpjT/IaHgfMjw7g3IvQwlfatI404qbVPcatJwJO9rISfmSQmoXxPEifKWzmR6dR4tQeLcX91dLD94oPN9FdVOj06flv31J7rReyxrEPczlHS6MfBev+7wJeu07iSQjDRiq483xdl95ggcllZruRA9k3EuQfGIkxOpn2VjhZsedQCmGJum70vRXEYg/FUY7tGr/YM2KQdor9RxfY87nJYnVGupvCe/FlUcewUL2J+2bHTw7J4jZgvDB43oQvtaBH378Uf8lh8IZurjERsEmZzSSdUNuo4xlt1NcO4B/BrDCstzE3Bd0/Hz+AZ1+76KD+uS1tK5vDEoNNXfoW26XvPq4gQzR8cwGA0nQ2iSaec8DSr3NU51PWjTuN/bRqPRH8zZLKc1pqBxMKFmAydNuv4HPTzOzQrDGCQvUa9p13H4Ig8=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: wordpress-prod
    type: kubernetes.io/dockerconfigjson
