apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-prod # DIT IS DE KEY
resources:
  - ../../base
patches:
  - target:
      kind: PersistentVolumeClaim
      name: iscsi-test-pvc
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 2Gi
