---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  encryptedData:
    api-token: AgAyFX00HLxvUvIjm1X8ZpiGIwRnYxFbsifqKhAz5tZ2LIywKSzL7PerEOhvrSDUGJ1MVL3Wk23i7mCbok1WIE3r2msK6DIxp1vV95Z3rOqcgQmIn7VU5+bxfSub0Ep3YIoxgBJR3/JdDODEB7k4mb/GyGb8spxS4qXOhjZxt1S5sOerUUye2E1ig3W/Fo8ZvOxrYRxtrWqibHGK1EbvxUWeKDEggs2QzOMT4HPVcUpB3B9yTwXEA7rr2yr0vLQaOjTxbw/2NIctCaWtR1ONv1HKJiNNEWBn9lP5V5rg5V/gzVEaDHn+rqcW3di9oWTEy3xFqoH4mWWOTfdlyTOEGBWV5pRzMZyrnWjl7XyUB0fs/n94ake+WOnIXMG1XPCmBVFP5vgg7tqUpktlGq8s7nAiQQ2r9WjjNsbzoM6JpH+KtnbCdGT6+PegKk5OVzSFswSqgmNK/wXrHx7P0Ni0jLkqY0hsgwBrlvQw7vH9ac0gWWmDN0L9cIMwsaVXJvvSDCH4ov2+xVtPtnWd/YLMmcXnvWpb7lmrzl52A9D5Y1RZMbVee+8d5A9zAoIEEkPAM8Y4QmeX+NKn7lZsNLIBHls8ZE8GK0QMxdgCpLB7GUFBKj1rF7QFnSy33sbAjYDVvsLiceYJ2zBrGQ5wHjhs0EJ+HjE+GXgXSJVw0twZvVEILfwqmBCMTvyRmlMbPRsUtEzvmd5Hwia+oVD1VLA2fMrHgVgOKHnK5tsu0GCTqCR+ahIAAr/2+Jiy
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
